[package]

name = "s2protocol"
version = "0.0.1"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]

[dependencies]
byteorder = "0.3"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf.git"
path = "pfh"

[dependencies.phf_macros]
git = "https://github.com/sfackler/rust-phf.git"
